# 应用程序配置

# 基础配置
app:
  secret_key: "dev-secret-key"
  debug: true  # 调试模式开关

# 数据库配置
database:
  url: "mysql+pymysql://root:302811055wjhhz@localhost/cradle_message"
  track_modifications: false
  
# JWT配置
jwt:
  secret_key: "jwt-secret-key"
  access_token_expires_hours: 1

# 文件上传配置
uploads:
  max_content_length: 16777216  # 16MB
  
# 预警时间配置（单位：天）
alerts:
  first: 90    # 3个月
  second: 30   # 1个月
  third: 30    # 1个月
  fourth: 7    # 1周
  final: 1     # 1天
  
# 管理员配置
admin:
  username: "admin"
  password: "admin123"
  
# 加密配置
encryption:
  key: "encryption-key-32-bytes-long" 